apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: sergey/profile-service
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DATABASE 
              value: "mailing"
            - name: POSTGRES_HOST
              value: "postgresql"
            - name: JWT_SECRET
              value: "secret"
          ports:
            - name: http
              containerPort: 3146
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
spec:
  selector:
    app: profile-service
  ports:
    - name: http
      port: 80
      targetPort: 3146
      nodePort: 30002
  type: NodePort
